# permissions for end users to view resourcelimiters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcelimiter-viewer-role
rules:
- apiGroups:
  - resources.resourcelimiter.io
  resources:
  - resourcelimiters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resources.resourcelimiter.io
  resources:
  - resourcelimiters/status
  verbs:
  - get
