---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: resourceadminrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.resourcelimiter.io
  resources:
  - resourcelimiters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.resourcelimiter.io
  resources:
  - resourcelimiters/finalizers
  verbs:
  - update
- apiGroups:
  - resources.resourcelimiter.io
  resources:
  - resourcelimiters/status
  verbs:
  - get
  - patch
  - update
