{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.serviceAccount.namespace }}
  name: {{ include "resourcelimiter-converter.serviceAccountName" . }}
  labels:
    {{- include "resourcelimiter-converter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
