apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterroleName }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.resourcelimiter.io
  resources:
  - resourcelimiters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.resourcelimiter.io
  resources:
  - resourcelimiters/finalizers
  verbs:
  - delete
  - update
- apiGroups:
  - resources.resourcelimiter.io
  resources:
  - resourcelimiters/status
  verbs:
  - get
  - patch
  - update
- apiGroups: 
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - delete
  - list 
  - patch 
  - update 
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - update
  - create

