name: Main

on:
   push:
    branches:
      - main
   schedule:
    - cron: "0 12 * * *"
   workflow_dispatch:

env:
  GO111MODULE: on

jobs:
  build:
   runs-on: [self-hosted, Linux, dev-01]

   steps:
   - uses: actions/checkout@v3
     name: Checkout Code
     with:
        repository: chenliu1993/resourcelimiter
        ssh-key: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

   - name: Build images
     run: make docker-all-build

   - name: Push images
     run: make docker-all-push
  
   - name: Push helm
     run: make helm-all-push
