name: Main

on:
   push:
    branches:
      - main
   schedule:
    - cron: "0 12 * * *"

env:
  GO111MODULE: on

jobs:
  build:
   runs-on: [self-hosted, Linux, dev-01]

   steps:
   - name: Set up cluster
     run: kind delete cluster; kind create cluster --config /disk1/cliu/kind-config.yaml; sleep 60s;

   - uses: actions/checkout@v3
     name: Checkout Code
     with:
        repository: chenliu1993/resourcelimiter
        ssh-key: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

   - name: Build 
     run: make build

   - name: Test
     run: make test

  clean:
    runs-on: [self-hosted, Linux, dev-01]
    needs: [build]

    if: ${{ always() }}
    steps:
    - name: Clean up Test Cluster
      run: kind delete cluster
