name: Pull

on:
  pull_request:
  workflow_dispatch:

env:
  GO111MODULE: on

jobs:
  unit-test:
   runs-on: [self-hosted, Linux, dev-01]
  
   steps:

   - uses: actions/checkout@v3
     name: Checkout Code
     with:
        repository: chenliu1993/resourcelimiter
        ssh-key: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        

   - name: unit tests
     run: make unit-test 

    
