name: Pull

on:
  pull_request:
  workflow_dispatch:

env:
  GO111MODULE: on

jobs:
  build:
   runs-on: [self-hosted, Linux, dev-01]
  
   steps:
  #  - uses: actions/setup-go@v3
  #    with:
  #     go-version: '1.18'

   - name: Set up cluster
     run: kind delete cluster; kind create cluster; sleep 40s;

   - uses: actions/checkout@v3
     name: Checkout Code
     with:
        repository: chenliu1993/resourcelimiter
        ssh-key: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        
   - name: Build 
     run: make build

   - name: Test
     run: make test

    